"""Connector handoff payloads for Jira, GitHub and Slack."""
from __future__ import annotations

from typing import Any, Dict, List

from services.portfolio_demo_service import hero_output_shape
from services.real_connectors_service import create_github_issue, create_jira_issue, post_slack_message


def build_jira_payload(output: Dict[str, Any] | None = None) -> Dict[str, Any]:
    output = output or hero_output_shape()
    ticket = (output.get("jira_tickets") or [{}])[0]
    description = "\n".join([
        "Portfolio-generated Jira handoff for SAF-T/e-invoicing hero case.",
        "",
        "Acceptance criteria:",
        *[f"- {item}" for item in ticket.get("acceptance_criteria", [])],
        "",
        "Linked obligations:",
        *[f"- {item}" for item in ticket.get("linked_obligations", [])],
        "",
        "QA gate: mandatory negative test coverage required.",
    ])
    return {
        "fields": {
            "project": {"key": "SAFT"},
            "summary": ticket.get("summary", "Validate SAF-T invoice fields and traceability"),
            "issuetype": {"name": "Story"},
            "description": {
                "type": "doc",
                "version": 1,
                "content": [{"type": "paragraph", "content": [{"type": "text", "text": description}]}],
            },
            "labels": ["portfolio", "ai-pm", "compliance", "qa-negative-coverage"],
        }
    }


def build_github_issue_payload(output: Dict[str, Any] | None = None) -> Dict[str, Any]:
    output = output or hero_output_shape()
    ticket = (output.get("jira_tickets") or [{}])[0]
    body = "\n".join([
        "## Portfolio handoff",
        "SAF-T/e-invoicing compliance-to-product traceability.",
        "",
        "## Acceptance criteria",
        *[f"- [ ] {item}" for item in ticket.get("acceptance_criteria", [])],
        "",
        "## Required QA gate",
        "- [ ] Each linked obligation has at least one mapped negative/edge/failure test.",
    ])
    return {"title": ticket.get("summary", "Validate SAF-T invoice fields and traceability"), "body": body, "labels": ["portfolio", "compliance", "qa"]}


def build_slack_payload(output: Dict[str, Any] | None = None) -> Dict[str, Any]:
    output = output or hero_output_shape()
    return {
        "text": "SAF-T/e-invoicing hero workflow reviewed",
        "blocks": [
            {"type": "section", "text": {"type": "mrkdwn", "text": "*Portfolio handoff:* SAF-T/e-invoicing workflow is ready for review."}},
            {"type": "section", "text": {"type": "mrkdwn", "text": "*Gate:* mandatory negative test coverage must be passed before release-ready status."}},
            {"type": "context", "elements": [{"type": "mrkdwn", "text": "Generated by AI Product Intelligence Suite portfolio prototype."}]},
        ],
    }


def handoff_payloads(output: Dict[str, Any] | None = None) -> List[Dict[str, Any]]:
    output = output or hero_output_shape()
    return [
        {"connector": "Jira", "payload": build_jira_payload(output), "default_mode": "local_outbox"},
        {"connector": "GitHub", "payload": build_github_issue_payload(output), "default_mode": "local_outbox"},
        {"connector": "Slack", "payload": build_slack_payload(output), "default_mode": "local_outbox"},
    ]


def send_or_save(connector: str, payload: Dict[str, Any], *, live: bool, actor: str, role: str) -> Dict[str, Any]:
    key = connector.strip().lower()
    if key == "jira":
        return create_jira_issue(payload, live=live, actor=actor, role=role)
    if key == "github":
        return create_github_issue(payload, live=live, actor=actor, role=role)
    if key == "slack":
        return post_slack_message(payload, live=live, actor=actor, role=role)
    raise ValueError(f"Unsupported connector: {connector}")
