"""Honest limitations, benchmark and evaluation page."""
from __future__ import annotations

import json
from pathlib import Path

import streamlit as st

from ui.visual_components import render_card, render_metric_pill, render_score_bar


ROOT = Path(__file__).resolve().parents[1]


def _load_json(path: Path):
    if not path.exists():
        return None
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def render_limitations_page() -> None:
    st.header("Limitations & Benchmark")
    st.caption(
        "This page shows what is verified by code, "
        "what is model-generated, and what still requires human/product validation."
    )

    st.markdown("## What is actually verified")
    c1, c2, c3 = st.columns(3)
    with c1:
        render_card(
            "Rule-verified grounding",
            [
                "Citation IDs must exist in retrieved source chunks.",
                "Generated claims are compared with cited chunks using token containment, quote integrity and textual support checks.",
                "Each obligation can be mapped to a best supporting quote.",
                "Weak support is flagged for human review.",
            ],
            "🧾",
        )
    with c2:
        render_card(
            "Model-generated outputs",
            [
                "Requirements, risks, release notes and summaries are generated by the model.",
                "Model confidence labels are treated as advisory, not evidence.",
                "Human review remains required for compliance-sensitive use.",
            ],
            "🧠",
        )
    with c3:
        render_card(
            "Not yet production-grade",
            [
                "No authentication/RBAC in this portfolio demo.",
                "No persistent enterprise audit store by default.",
                "No independent human benchmark has been completed yet.",
            ],
            "⚠️",
        )

    st.markdown("## Mini benchmark status")
    benchmark = _load_json(ROOT / "benchmark" / "results" / "interpret_retrieval_benchmark.json")
    obligation_benchmark = _load_json(ROOT / "benchmark" / "results" / "interpret_obligation_benchmark.json")
    if benchmark:
        st.markdown("**Retrieval benchmark**")
        cols = st.columns(4)
        cols[0].metric("Questions", benchmark.get("questions"))
        cols[1].metric("Retrieval hit rate", f"{benchmark.get('retrieval_hit_rate', 0):.0%}")
        cols[2].metric("Average top score", f"{benchmark.get('average_top_score', 0):.2f}")
        cols[3].metric("Evaluation type", benchmark.get("evaluation_type", "N/A"))
        st.dataframe(benchmark.get("rows", []), width="stretch", hide_index=True)
    else:
        st.info("Run `python scripts/run_interpret_benchmark.py` to generate local retrieval benchmark results.")

    if obligation_benchmark:
        st.markdown("**Obligation extraction benchmark**")
        cols = st.columns(4)
        cols[0].metric("Gold obligations", obligation_benchmark.get("gold_count"))
        cols[1].metric("Precision proxy", f"{obligation_benchmark.get('precision_proxy', 0)}%")
        cols[2].metric("Recall proxy", f"{obligation_benchmark.get('recall_proxy', 0)}%")
        cols[3].metric("F1 proxy", f"{obligation_benchmark.get('f1_proxy', 0)}%")
        st.dataframe(obligation_benchmark.get("match_matrix", []), width="stretch", hide_index=True)
    else:
        st.info("Run `python scripts/run_interpret_obligation_benchmark.py` to generate local obligation benchmark results.")

    st.markdown("## Evaluation methodology")
    st.markdown(
        """
The project now separates **three different signal types**:

1. **Model output** — generated artefacts such as obligations, product requirements and release notes.
2. **Rule-verified checks** — deterministic checks such as source-ID existence, claim/chunk lexical support and risky wording detection.
3. **Human validation** — the final authority for compliance interpretation, legal meaning and production use.

The system deliberately avoids presenting model self-assessments as objective truth.
"""
    )

    st.markdown("## Current known limitations")
    st.warning(
        "This is a portfolio-grade prototype. It demonstrates product thinking, RAG workflow design and responsible-AI guardrails. "
        "It is not a production compliance system and does not provide legal advice."
    )
    st.markdown(
        """
- Citation support checking is a rule-based support check, not a formal proof that a legal obligation exists.
- Quote-level grounding checks whether source text supports a generated claim; it does not prove the legal interpretation is complete.
- Demo Mode uses deterministic local embeddings for cost-free testing; API Mode uses OpenAI embeddings.
- Benchmarks are synthetic until tested on a larger public dataset.
- Public demo should use synthetic or public documents only.
- Any real enterprise deployment would require authentication, permissions, document security, audit retention and observability.
"""
    )

    st.markdown("## Responsible roadmap")
    render_score_bar("Current portfolio maturity", 78, "Good prototype; needs public demo and larger evaluation")
    render_score_bar("Interpret module credibility", 86, "Source quotes, citation support checks, human review queue and obligation benchmark now included")
    render_score_bar("Production readiness", 48, "Requires auth, RBAC, security, observability and integrations")
